CREATE TABLE IF NOT EXISTS BILL
(
    BILL_ID				BIGSERIAL PRIMARY KEY,
    BILL_CODE        	VARCHAR(50) NOT NULL,
    ORDER_ID			INTEGER NOT NULL,
    ORDER_TOTAL_PRICE 	NUMERIC,
    CUSTOMER_ID 		INTEGER NOT NULL,	
    PAYMENT				NUMERIC NOT NULL,
    TIP					NUMERIC,
    PROMOTION_ID		INTEGER,
    PROMOTION_COST		NUMERIC,
    EMPLOYEE_ID			INTEGER NOT NULL,
    CREATED_DATETIME  	TIMESTAMP WITH TIME ZONE,
    UPDATED_BY          VARCHAR(100),
    CONSTRAINT BILL_CODE_UNIQUE UNIQUE (BILL_CODE),
    CONSTRAINT BILL_ORDER_FK_1 FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID),
    CONSTRAINT BILL_CUSTOMER_FK_1 FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID)
);